### ISSUE TITLE
Can't load since 0.0.6

### ISSUE THREAD

**Issue by pandaquests** [giacomocerquone/opencv-react#9]
Hi there,

Since 0.0.6 I can't load opencv-react anymore. I have to resort to 0.0.5.

**Comment by giacomocerquone** [comment]
can you paste the error?

**Comment by pandaquests** [comment]
There are no error messages. It just doesn't load.

**Comment by giacomocerquone** [comment]
Hey there, I've only had now the time to care for this small lib a bit.
I tried to start the example project and it didn't work due to some stuff merged from a pull request.

I fixed the problem (so no need to republish) and also create a github action to publish the example over here: https://giacomocerquone.github.io/opencv-react/.

As you can see, it works. I'm sorry it doesn't for you!
If you can create a repro on a repo, I can take a look at it, but for now I'm going to close this.
